import {
  AKSHAY_SAINI,
  BACKEND,
  CLOSURES,
  DESIGN_PATTERNS,
  FRONTEND,
  HOISTING,
  JAVASCRIPT,
  NEWBIE,
  NODEJS,
  REACT,
  WEB_COMPONENTS,
} from "../../../data/blog";

export const NOTES_CARD_DATA = [
  {
    title: "Namaste Node JS",
    by: "Akshay Saini",
    sourceName: "Namaste Dev ",
    sourceLink: "https://namastedev.com/",
    lastUpdated: "",
    publishedOn: "17 Aug 2024",
    thumbnailUrl: "https://i.ibb.co/2hq8tjW/akshays-banner.jpg",
    isProgress: true,
    isComingSoon: false,
    tags: [BACKEND, NODEJS, AKSHAY_SAINI],
    githubLink: "#",
    route: "/digital-notes/notes/namaste-node-js",
    shortDesc: ` Get the best-explained notes for each chapter of the Namaste Node.js
            course by Akshay Saini. These notes are written by Ashutosh and can
            be edited on GitHub.`,
  },
  {
    title: "JS Quick Snippets",
    by: "Ashutosh Anand Tiwari",
    sourceName: "Google..etc.. ",
    sourceLink: "https://google.com/",
    lastUpdated: "",
    publishedOn: "21 Aug 2024",
    thumbnailUrl: "https://i.ibb.co/x7kYDW1/snippets.jpg",
    isProgress: false,
    isComingSoon: false,
    tags: [FRONTEND, NEWBIE, JAVASCRIPT],
    githubLink: "#",
    route: "/digital-notes/notes/javascript-snippets",
    shortDesc: ` Dive into our digital garden for 100+ JavaScript code snippets—perfect for interview prep or brushing up on your skills!  🚀`,
  },
  // {
  //   title: 'Backend with NodeJs',
  //   by: 'ProCodrr | Anurag Singh',
  //   sourceName:'ProCodrr',
  //   sourceLink:'https://app.procodrr.com/web/checkout/66c86939c0a286ccc32c0d8b',
  //   lastUpdated:'',
  //   publishedOn:'',
  //   thumbnailUrl:'https://tagmango.com/publicassets/-backend-with-nodejs-1-f59defad2193f9e9223bfa2a3ad3ac47.png',
  //   isProgress:false,
  //   isComingSoon:false,
  //   tags:['nodejs', 'deep', 'procdrr', NEWBIE, JAVASCRIPT, 'hindi'],
  //   githubLink:'#',
  //   route:'/tech/notes/backend-with-nodejs-by-procoderr-notes-by-ashutosh-anand-tiwari',

  // },

  {
    title: "YDKJS: Up & Going",
    by: "Kyle Simpson",
    sourceName: "Book ",
    sourceLink: "https://me.getify.com/",
    lastUpdated: "",
    publishedOn: "",
    thumbnailUrl:
      "https://image.ebooks.com/cover/1993212.jpg?width=166&height=250&quality=85",
    isProgress: false,
    isComingSoon: true,
    tags: [FRONTEND, "book", "js-basics"],
    githubLink: "#",
    route: "/tech/notes/namaste-frontend",
  },
  {
    title: "YDKJS: Scope & Closures",
    by: "Kyle Simpson",
    sourceName: "Book ",
    sourceLink: "https://me.getify.com/",
    lastUpdated: "",
    publishedOn: "",
    thumbnailUrl:
      "https://image.ebooks.com/cover/1647631.jpg?width=166&height=250&quality=85",
    isProgress: false,
    isComingSoon: true,
    tags: [FRONTEND, "book", "js-basics"],
    githubLink: "#",
    route: "/tech/notes/namaste-frontend",
  },
  // {
  //   title: 'You Don`t know JS: this & Object',
  //   by: 'Kyle Simpson',
  //   sourceName:'Book ',
  //   sourceLink:'https://me.getify.com/',
  //   lastUpdated:'',
  //   publishedOn:'',
  //   thumbnailUrl:'https://image.ebooks.com/cover/1734321.jpg?width=166&height=250&quality=85',
  //   isProgress:false,
  //   isComingSoon:true,
  //   tags:[FRONTEND, 'book', 'js-basics'],
  //   githubLink:'#',
  //   route:'/tech/notes/namaste-frontend',

  // },
  // {
  //   title: 'You Don`t know JS: Types & Grammar',
  //   by: 'Kyle Simpson',
  //   sourceName:'Book ',
  //   sourceLink:'https://me.getify.com/',
  //   lastUpdated:'',
  //   publishedOn:'',
  //   thumbnailUrl:'https://image.ebooks.com/cover/1935541.jpg?width=166&height=250&quality=85',
  //   isProgress:false,
  //   isComingSoon:true,
  //   tags:[FRONTEND, 'kyle-simpson', 'book', 'js-basics'],
  //   githubLink:'#',
  //   route:'/tech/notes/namaste-frontend',

  // },
  {
    title: "Namaste JavaScript",
    by: "Akshay Saini",
    sourceName: "Namaste Dev & Youtube ",
    sourceLink: "https://namastedev.com/",
    lastUpdated: "",
    publishedOn: "",
    thumbnailUrl: "https://i.ibb.co/kg0j4Bf/namaste-JS.jpg",

    isProgress: false,
    isComingSoon: true,
    tags: [FRONTEND, NEWBIE, REACT],
    githubLink: "#",
    route: "/tech/notes/namaste-js",
  },
  {
    title: "Namaste React",
    by: "Akshay Saini",
    sourceName: "Namaste  ",
    sourceLink: "https://namastedev.com/",
    lastUpdated: "",
    publishedOn: "",
    thumbnailUrl: "https://i.ibb.co/68Mvg2V/react.jpg",
    isProgress: false,
    isComingSoon: true,
    tags: [FRONTEND, NEWBIE, REACT],
    githubLink: "#",
    route: "/tech/notes/namaste-react",
  },
  // {
  //   title: 'Namaste Frontend Design System',
  //   by: 'Akshay Saini',
  //   sourceName:'Namaste Dev ',
  //   sourceLink:'https://namastedev.com/',
  //   lastUpdated:'',
  //   publishedOn:'',
  //   thumbnailUrl:'https://i.ibb.co/4JDMt9d/fds.jpg',
  //   isProgress:false,
  //   isComingSoon:true,
  //   tags:[FRONTEND, AKSHAY_SAINI, NEWBIE, DESIGN_PATTERNS, WEB_COMPONENTS],
  //   githubLink:'#',
  //   route:'/tech/notes/namaste-frontend',

  // },
];
